#!/bin/bash

vncserver-x11 -service -joinCloud eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJWMXlPVXE5bkNXYWhmYUZwWXlrIiwiYXVkIjoiY3JlYXRlLXNlcnZlciIsImlzcyI6InBsYXRmb3JtLWVudGVycHJpc2UtcG9ydGFsOm1Da1VBbjZjbnBnMkVpaHdYSDIiLCJpZCI6Ik5mWWhicW5aR0ZLdG9EcVZvVWlqIiwiaWF0IjoxNTQzNTY0MzIyfQ.UaUyIPHJiBCce5HEbpdsCsWhTbY-ydiV5-V1_cmwtjA